### ISSUE TITLE
Project dashboard component

### ISSUE THREAD

**Issue by seanknox** [Azure/kashti#117]
Up to implementer to break this into multiple stories where first story is implementation of cards (with styling) but with placeholder text + with tests

* ultimate result should be same card layout as existing kashti + styling
* use foundation sites for grid, use column for approximate size as existing kashti sidebar
* cards are not hyperlinked yet (no projects page exists yet)
* project title should truncate with ellipsis at ~30 characters

Related work: 
## Sidebar
- [x] #115 Initial sidebar component
- [x] #127 Add sidebar icons and HREFs

## Footer
- [x] #116 Footer component

## Main content
- [x] #128 Main Dashboard layout
- [x] #129 Dashboard loads projects from Brigade

**Comment by seanknox** [comment]
Closed via #144
